master_secret = "CHANGE_ME!!!"

host = "localhost" # default
port = 8000        # default

# removing this line will default to moz_json formatted logs (which is preferred for production envs)
human_logs = 1

# MySQL DSN:
syncstorage.database_url = "mysql://ffsync:**topsecret**@localhost/ffsync?socket=%2Fvar%2Flib%2Fmysql%2Fmysql.sock"

# disable quota limits
syncstorage.enable_quota = 0
# set the quota limit to 2GB.
# max_quota_limit = 200000000
syncstorage.enabled = true
syncstorage.limits.max_total_records = 1666 # See issues #298/#333

# MySQL DSN (same as above, as table names are distinct
tokenserver.database_url = "mysql://ffsync:**topsecret**@localhost/ffsync?socket=%2Fvar%2Flib%2Fmysql%2Fmysql.sock"

tokenserver.enabled = true
tokenserver.run_migrations = true
tokenserver.fxa_email_domain = "api.accounts.firefox.com"
tokenserver.fxa_oauth_server_url = "https://oauth.accounts.firefox.com"
tokenserver.fxa_browserid_audience = "https://token.services.mozilla.comn"
tokenserver.fxa_browserid_issuer = "https://api.accounts.firefox.com"
tokenserver.fxa_browserid_server_url = "https://verifier.accounts.firefox.com"

# cors settings
# cors_allowed_origin = "localhost"
# cors_max_age = 86400
