name: Publish

on:
  workflow_call:
    inputs:
      artifact-name:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      artifact-name:
        required: true
        type: string
 
jobs:
  publish-ppa:
    name: Publish to LaunchPad PPA
    runs-on: ubuntu-latest
    steps:
    - name: Fetch artifacts
      uses: actions/download-artifact@v5
      with:
        name: ${{ inputs.artifact-name }}
    - name: Install dput
      run: DEBIAN_FRONTEND=noninteractive apt-get install -y dput
    - name: Publish to PPA
      run: dput ppa:felfert/syncstorage-rs *_source.changes
